/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as FeaturesClerkRouteRouteImport } from './routes/features/clerk/route'
import { Route as FeaturesAuthenticatedRouteRouteImport } from './routes/features/_authenticated/route'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as FeaturesAuthenticatedIndexRouteImport } from './routes/features/_authenticated/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as Featureserrors503RouteImport } from './routes/features/(errors)/503'
import { Route as Featureserrors500RouteImport } from './routes/features/(errors)/500'
import { Route as Featureserrors404RouteImport } from './routes/features/(errors)/404'
import { Route as Featureserrors403RouteImport } from './routes/features/(errors)/403'
import { Route as Featureserrors401RouteImport } from './routes/features/(errors)/401'
import { Route as FeaturesauthSignUpRouteImport } from './routes/features/(auth)/sign-up'
import { Route as FeaturesauthSignIn2RouteImport } from './routes/features/(auth)/sign-in-2'
import { Route as FeaturesauthSignInRouteImport } from './routes/features/(auth)/sign-in'
import { Route as FeaturesauthOtpRouteImport } from './routes/features/(auth)/otp'
import { Route as FeaturesauthForgotPasswordRouteImport } from './routes/features/(auth)/forgot-password'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as FeaturesClerkAuthenticatedRouteRouteImport } from './routes/features/clerk/_authenticated/route'
import { Route as FeaturesClerkauthRouteRouteImport } from './routes/features/clerk/(auth)/route'
import { Route as FeaturesAuthenticatedSettingsRouteRouteImport } from './routes/features/_authenticated/settings/route'
import { Route as FeaturesAuthenticatedUsersIndexRouteImport } from './routes/features/_authenticated/users/index'
import { Route as FeaturesAuthenticatedTasksIndexRouteImport } from './routes/features/_authenticated/tasks/index'
import { Route as FeaturesAuthenticatedSettingsIndexRouteImport } from './routes/features/_authenticated/settings/index'
import { Route as FeaturesAuthenticatedHelpCenterIndexRouteImport } from './routes/features/_authenticated/help-center/index'
import { Route as FeaturesAuthenticatedChatsIndexRouteImport } from './routes/features/_authenticated/chats/index'
import { Route as FeaturesAuthenticatedAppsIndexRouteImport } from './routes/features/_authenticated/apps/index'
import { Route as FeaturesClerkAuthenticatedUserManagementRouteImport } from './routes/features/clerk/_authenticated/user-management'
import { Route as FeaturesClerkauthSignUpRouteImport } from './routes/features/clerk/(auth)/sign-up'
import { Route as FeaturesClerkauthSignInRouteImport } from './routes/features/clerk/(auth)/sign-in'
import { Route as FeaturesAuthenticatedSettingsNotificationsRouteImport } from './routes/features/_authenticated/settings/notifications'
import { Route as FeaturesAuthenticatedSettingsDisplayRouteImport } from './routes/features/_authenticated/settings/display'
import { Route as FeaturesAuthenticatedSettingsAppearanceRouteImport } from './routes/features/_authenticated/settings/appearance'
import { Route as FeaturesAuthenticatedSettingsAccountRouteImport } from './routes/features/_authenticated/settings/account'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesClerkRouteRoute = FeaturesClerkRouteRouteImport.update({
  id: '/features/clerk',
  path: '/features/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesAuthenticatedRouteRoute =
  FeaturesAuthenticatedRouteRouteImport.update({
    id: '/features/_authenticated',
    path: '/features',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const FeaturesAuthenticatedIndexRoute =
  FeaturesAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => FeaturesAuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Featureserrors503Route = Featureserrors503RouteImport.update({
  id: '/features/(errors)/503',
  path: '/features/503',
  getParentRoute: () => rootRouteImport,
} as any)
const Featureserrors500Route = Featureserrors500RouteImport.update({
  id: '/features/(errors)/500',
  path: '/features/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Featureserrors404Route = Featureserrors404RouteImport.update({
  id: '/features/(errors)/404',
  path: '/features/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Featureserrors403Route = Featureserrors403RouteImport.update({
  id: '/features/(errors)/403',
  path: '/features/403',
  getParentRoute: () => rootRouteImport,
} as any)
const Featureserrors401Route = Featureserrors401RouteImport.update({
  id: '/features/(errors)/401',
  path: '/features/401',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesauthSignUpRoute = FeaturesauthSignUpRouteImport.update({
  id: '/features/(auth)/sign-up',
  path: '/features/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesauthSignIn2Route = FeaturesauthSignIn2RouteImport.update({
  id: '/features/(auth)/sign-in-2',
  path: '/features/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesauthSignInRoute = FeaturesauthSignInRouteImport.update({
  id: '/features/(auth)/sign-in',
  path: '/features/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesauthOtpRoute = FeaturesauthOtpRouteImport.update({
  id: '/features/(auth)/otp',
  path: '/features/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesauthForgotPasswordRoute =
  FeaturesauthForgotPasswordRouteImport.update({
    id: '/features/(auth)/forgot-password',
    path: '/features/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const FeaturesClerkAuthenticatedRouteRoute =
  FeaturesClerkAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => FeaturesClerkRouteRoute,
  } as any)
const FeaturesClerkauthRouteRoute = FeaturesClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => FeaturesClerkRouteRoute,
} as any)
const FeaturesAuthenticatedSettingsRouteRoute =
  FeaturesAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => FeaturesAuthenticatedRouteRoute,
  } as any)
const FeaturesAuthenticatedUsersIndexRoute =
  FeaturesAuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => FeaturesAuthenticatedRouteRoute,
  } as any)
const FeaturesAuthenticatedTasksIndexRoute =
  FeaturesAuthenticatedTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => FeaturesAuthenticatedRouteRoute,
  } as any)
const FeaturesAuthenticatedSettingsIndexRoute =
  FeaturesAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => FeaturesAuthenticatedSettingsRouteRoute,
  } as any)
const FeaturesAuthenticatedHelpCenterIndexRoute =
  FeaturesAuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => FeaturesAuthenticatedRouteRoute,
  } as any)
const FeaturesAuthenticatedChatsIndexRoute =
  FeaturesAuthenticatedChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => FeaturesAuthenticatedRouteRoute,
  } as any)
const FeaturesAuthenticatedAppsIndexRoute =
  FeaturesAuthenticatedAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => FeaturesAuthenticatedRouteRoute,
  } as any)
const FeaturesClerkAuthenticatedUserManagementRoute =
  FeaturesClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => FeaturesClerkAuthenticatedRouteRoute,
  } as any)
const FeaturesClerkauthSignUpRoute = FeaturesClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => FeaturesClerkauthRouteRoute,
} as any)
const FeaturesClerkauthSignInRoute = FeaturesClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => FeaturesClerkauthRouteRoute,
} as any)
const FeaturesAuthenticatedSettingsNotificationsRoute =
  FeaturesAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => FeaturesAuthenticatedSettingsRouteRoute,
  } as any)
const FeaturesAuthenticatedSettingsDisplayRoute =
  FeaturesAuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => FeaturesAuthenticatedSettingsRouteRoute,
  } as any)
const FeaturesAuthenticatedSettingsAppearanceRoute =
  FeaturesAuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => FeaturesAuthenticatedSettingsRouteRoute,
  } as any)
const FeaturesAuthenticatedSettingsAccountRoute =
  FeaturesAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => FeaturesAuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/features': typeof FeaturesAuthenticatedRouteRouteWithChildren
  '/features/clerk': typeof FeaturesClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/features/settings': typeof FeaturesAuthenticatedSettingsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/features/forgot-password': typeof FeaturesauthForgotPasswordRoute
  '/features/otp': typeof FeaturesauthOtpRoute
  '/features/sign-in': typeof FeaturesauthSignInRoute
  '/features/sign-in-2': typeof FeaturesauthSignIn2Route
  '/features/sign-up': typeof FeaturesauthSignUpRoute
  '/features/401': typeof Featureserrors401Route
  '/features/403': typeof Featureserrors403Route
  '/features/404': typeof Featureserrors404Route
  '/features/500': typeof Featureserrors500Route
  '/features/503': typeof Featureserrors503Route
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/features/': typeof FeaturesAuthenticatedIndexRoute
  '/features/settings/account': typeof FeaturesAuthenticatedSettingsAccountRoute
  '/features/settings/appearance': typeof FeaturesAuthenticatedSettingsAppearanceRoute
  '/features/settings/display': typeof FeaturesAuthenticatedSettingsDisplayRoute
  '/features/settings/notifications': typeof FeaturesAuthenticatedSettingsNotificationsRoute
  '/features/clerk/sign-in': typeof FeaturesClerkauthSignInRoute
  '/features/clerk/sign-up': typeof FeaturesClerkauthSignUpRoute
  '/features/clerk/user-management': typeof FeaturesClerkAuthenticatedUserManagementRoute
  '/features/apps/': typeof FeaturesAuthenticatedAppsIndexRoute
  '/features/chats/': typeof FeaturesAuthenticatedChatsIndexRoute
  '/features/help-center/': typeof FeaturesAuthenticatedHelpCenterIndexRoute
  '/features/settings/': typeof FeaturesAuthenticatedSettingsIndexRoute
  '/features/tasks/': typeof FeaturesAuthenticatedTasksIndexRoute
  '/features/users/': typeof FeaturesAuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/features/clerk': typeof FeaturesClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/features/forgot-password': typeof FeaturesauthForgotPasswordRoute
  '/features/otp': typeof FeaturesauthOtpRoute
  '/features/sign-in': typeof FeaturesauthSignInRoute
  '/features/sign-in-2': typeof FeaturesauthSignIn2Route
  '/features/sign-up': typeof FeaturesauthSignUpRoute
  '/features/401': typeof Featureserrors401Route
  '/features/403': typeof Featureserrors403Route
  '/features/404': typeof Featureserrors404Route
  '/features/500': typeof Featureserrors500Route
  '/features/503': typeof Featureserrors503Route
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/features': typeof FeaturesAuthenticatedIndexRoute
  '/features/settings/account': typeof FeaturesAuthenticatedSettingsAccountRoute
  '/features/settings/appearance': typeof FeaturesAuthenticatedSettingsAppearanceRoute
  '/features/settings/display': typeof FeaturesAuthenticatedSettingsDisplayRoute
  '/features/settings/notifications': typeof FeaturesAuthenticatedSettingsNotificationsRoute
  '/features/clerk/sign-in': typeof FeaturesClerkauthSignInRoute
  '/features/clerk/sign-up': typeof FeaturesClerkauthSignUpRoute
  '/features/clerk/user-management': typeof FeaturesClerkAuthenticatedUserManagementRoute
  '/features/apps': typeof FeaturesAuthenticatedAppsIndexRoute
  '/features/chats': typeof FeaturesAuthenticatedChatsIndexRoute
  '/features/help-center': typeof FeaturesAuthenticatedHelpCenterIndexRoute
  '/features/settings': typeof FeaturesAuthenticatedSettingsIndexRoute
  '/features/tasks': typeof FeaturesAuthenticatedTasksIndexRoute
  '/features/users': typeof FeaturesAuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/features/_authenticated': typeof FeaturesAuthenticatedRouteRouteWithChildren
  '/features/clerk': typeof FeaturesClerkRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/features/_authenticated/settings': typeof FeaturesAuthenticatedSettingsRouteRouteWithChildren
  '/features/clerk/(auth)': typeof FeaturesClerkauthRouteRouteWithChildren
  '/features/clerk/_authenticated': typeof FeaturesClerkAuthenticatedRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/features/(auth)/forgot-password': typeof FeaturesauthForgotPasswordRoute
  '/features/(auth)/otp': typeof FeaturesauthOtpRoute
  '/features/(auth)/sign-in': typeof FeaturesauthSignInRoute
  '/features/(auth)/sign-in-2': typeof FeaturesauthSignIn2Route
  '/features/(auth)/sign-up': typeof FeaturesauthSignUpRoute
  '/features/(errors)/401': typeof Featureserrors401Route
  '/features/(errors)/403': typeof Featureserrors403Route
  '/features/(errors)/404': typeof Featureserrors404Route
  '/features/(errors)/500': typeof Featureserrors500Route
  '/features/(errors)/503': typeof Featureserrors503Route
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/features/_authenticated/': typeof FeaturesAuthenticatedIndexRoute
  '/features/_authenticated/settings/account': typeof FeaturesAuthenticatedSettingsAccountRoute
  '/features/_authenticated/settings/appearance': typeof FeaturesAuthenticatedSettingsAppearanceRoute
  '/features/_authenticated/settings/display': typeof FeaturesAuthenticatedSettingsDisplayRoute
  '/features/_authenticated/settings/notifications': typeof FeaturesAuthenticatedSettingsNotificationsRoute
  '/features/clerk/(auth)/sign-in': typeof FeaturesClerkauthSignInRoute
  '/features/clerk/(auth)/sign-up': typeof FeaturesClerkauthSignUpRoute
  '/features/clerk/_authenticated/user-management': typeof FeaturesClerkAuthenticatedUserManagementRoute
  '/features/_authenticated/apps/': typeof FeaturesAuthenticatedAppsIndexRoute
  '/features/_authenticated/chats/': typeof FeaturesAuthenticatedChatsIndexRoute
  '/features/_authenticated/help-center/': typeof FeaturesAuthenticatedHelpCenterIndexRoute
  '/features/_authenticated/settings/': typeof FeaturesAuthenticatedSettingsIndexRoute
  '/features/_authenticated/tasks/': typeof FeaturesAuthenticatedTasksIndexRoute
  '/features/_authenticated/users/': typeof FeaturesAuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/features'
    | '/features/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/features/settings'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/features/forgot-password'
    | '/features/otp'
    | '/features/sign-in'
    | '/features/sign-in-2'
    | '/features/sign-up'
    | '/features/401'
    | '/features/403'
    | '/features/404'
    | '/features/500'
    | '/features/503'
    | '/apps/'
    | '/chats/'
    | '/help-center/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/features/'
    | '/features/settings/account'
    | '/features/settings/appearance'
    | '/features/settings/display'
    | '/features/settings/notifications'
    | '/features/clerk/sign-in'
    | '/features/clerk/sign-up'
    | '/features/clerk/user-management'
    | '/features/apps/'
    | '/features/chats/'
    | '/features/help-center/'
    | '/features/settings/'
    | '/features/tasks/'
    | '/features/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/features/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/features/forgot-password'
    | '/features/otp'
    | '/features/sign-in'
    | '/features/sign-in-2'
    | '/features/sign-up'
    | '/features/401'
    | '/features/403'
    | '/features/404'
    | '/features/500'
    | '/features/503'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/features'
    | '/features/settings/account'
    | '/features/settings/appearance'
    | '/features/settings/display'
    | '/features/settings/notifications'
    | '/features/clerk/sign-in'
    | '/features/clerk/sign-up'
    | '/features/clerk/user-management'
    | '/features/apps'
    | '/features/chats'
    | '/features/help-center'
    | '/features/settings'
    | '/features/tasks'
    | '/features/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/features/_authenticated'
    | '/features/clerk'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/features/_authenticated/settings'
    | '/features/clerk/(auth)'
    | '/features/clerk/_authenticated'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/features/(auth)/forgot-password'
    | '/features/(auth)/otp'
    | '/features/(auth)/sign-in'
    | '/features/(auth)/sign-in-2'
    | '/features/(auth)/sign-up'
    | '/features/(errors)/401'
    | '/features/(errors)/403'
    | '/features/(errors)/404'
    | '/features/(errors)/500'
    | '/features/(errors)/503'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/features/_authenticated/'
    | '/features/_authenticated/settings/account'
    | '/features/_authenticated/settings/appearance'
    | '/features/_authenticated/settings/display'
    | '/features/_authenticated/settings/notifications'
    | '/features/clerk/(auth)/sign-in'
    | '/features/clerk/(auth)/sign-up'
    | '/features/clerk/_authenticated/user-management'
    | '/features/_authenticated/apps/'
    | '/features/_authenticated/chats/'
    | '/features/_authenticated/help-center/'
    | '/features/_authenticated/settings/'
    | '/features/_authenticated/tasks/'
    | '/features/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  FeaturesAuthenticatedRouteRoute: typeof FeaturesAuthenticatedRouteRouteWithChildren
  FeaturesClerkRouteRoute: typeof FeaturesClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  FeaturesauthForgotPasswordRoute: typeof FeaturesauthForgotPasswordRoute
  FeaturesauthOtpRoute: typeof FeaturesauthOtpRoute
  FeaturesauthSignInRoute: typeof FeaturesauthSignInRoute
  FeaturesauthSignIn2Route: typeof FeaturesauthSignIn2Route
  FeaturesauthSignUpRoute: typeof FeaturesauthSignUpRoute
  Featureserrors401Route: typeof Featureserrors401Route
  Featureserrors403Route: typeof Featureserrors403Route
  Featureserrors404Route: typeof Featureserrors404Route
  Featureserrors500Route: typeof Featureserrors500Route
  Featureserrors503Route: typeof Featureserrors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/clerk': {
      id: '/features/clerk'
      path: '/features/clerk'
      fullPath: '/features/clerk'
      preLoaderRoute: typeof FeaturesClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/_authenticated': {
      id: '/features/_authenticated'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/features/_authenticated/': {
      id: '/features/_authenticated/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesAuthenticatedIndexRouteImport
      parentRoute: typeof FeaturesAuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/features/(errors)/503': {
      id: '/features/(errors)/503'
      path: '/features/503'
      fullPath: '/features/503'
      preLoaderRoute: typeof Featureserrors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/(errors)/500': {
      id: '/features/(errors)/500'
      path: '/features/500'
      fullPath: '/features/500'
      preLoaderRoute: typeof Featureserrors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/(errors)/404': {
      id: '/features/(errors)/404'
      path: '/features/404'
      fullPath: '/features/404'
      preLoaderRoute: typeof Featureserrors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/(errors)/403': {
      id: '/features/(errors)/403'
      path: '/features/403'
      fullPath: '/features/403'
      preLoaderRoute: typeof Featureserrors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/(errors)/401': {
      id: '/features/(errors)/401'
      path: '/features/401'
      fullPath: '/features/401'
      preLoaderRoute: typeof Featureserrors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/(auth)/sign-up': {
      id: '/features/(auth)/sign-up'
      path: '/features/sign-up'
      fullPath: '/features/sign-up'
      preLoaderRoute: typeof FeaturesauthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/(auth)/sign-in-2': {
      id: '/features/(auth)/sign-in-2'
      path: '/features/sign-in-2'
      fullPath: '/features/sign-in-2'
      preLoaderRoute: typeof FeaturesauthSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/(auth)/sign-in': {
      id: '/features/(auth)/sign-in'
      path: '/features/sign-in'
      fullPath: '/features/sign-in'
      preLoaderRoute: typeof FeaturesauthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/(auth)/otp': {
      id: '/features/(auth)/otp'
      path: '/features/otp'
      fullPath: '/features/otp'
      preLoaderRoute: typeof FeaturesauthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/(auth)/forgot-password': {
      id: '/features/(auth)/forgot-password'
      path: '/features/forgot-password'
      fullPath: '/features/forgot-password'
      preLoaderRoute: typeof FeaturesauthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/features/clerk/_authenticated': {
      id: '/features/clerk/_authenticated'
      path: ''
      fullPath: '/features/clerk'
      preLoaderRoute: typeof FeaturesClerkAuthenticatedRouteRouteImport
      parentRoute: typeof FeaturesClerkRouteRoute
    }
    '/features/clerk/(auth)': {
      id: '/features/clerk/(auth)'
      path: ''
      fullPath: '/features/clerk'
      preLoaderRoute: typeof FeaturesClerkauthRouteRouteImport
      parentRoute: typeof FeaturesClerkRouteRoute
    }
    '/features/_authenticated/settings': {
      id: '/features/_authenticated/settings'
      path: '/settings'
      fullPath: '/features/settings'
      preLoaderRoute: typeof FeaturesAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof FeaturesAuthenticatedRouteRoute
    }
    '/features/_authenticated/users/': {
      id: '/features/_authenticated/users/'
      path: '/users'
      fullPath: '/features/users/'
      preLoaderRoute: typeof FeaturesAuthenticatedUsersIndexRouteImport
      parentRoute: typeof FeaturesAuthenticatedRouteRoute
    }
    '/features/_authenticated/tasks/': {
      id: '/features/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/features/tasks/'
      preLoaderRoute: typeof FeaturesAuthenticatedTasksIndexRouteImport
      parentRoute: typeof FeaturesAuthenticatedRouteRoute
    }
    '/features/_authenticated/settings/': {
      id: '/features/_authenticated/settings/'
      path: '/'
      fullPath: '/features/settings/'
      preLoaderRoute: typeof FeaturesAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof FeaturesAuthenticatedSettingsRouteRoute
    }
    '/features/_authenticated/help-center/': {
      id: '/features/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/features/help-center/'
      preLoaderRoute: typeof FeaturesAuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof FeaturesAuthenticatedRouteRoute
    }
    '/features/_authenticated/chats/': {
      id: '/features/_authenticated/chats/'
      path: '/chats'
      fullPath: '/features/chats/'
      preLoaderRoute: typeof FeaturesAuthenticatedChatsIndexRouteImport
      parentRoute: typeof FeaturesAuthenticatedRouteRoute
    }
    '/features/_authenticated/apps/': {
      id: '/features/_authenticated/apps/'
      path: '/apps'
      fullPath: '/features/apps/'
      preLoaderRoute: typeof FeaturesAuthenticatedAppsIndexRouteImport
      parentRoute: typeof FeaturesAuthenticatedRouteRoute
    }
    '/features/clerk/_authenticated/user-management': {
      id: '/features/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/features/clerk/user-management'
      preLoaderRoute: typeof FeaturesClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof FeaturesClerkAuthenticatedRouteRoute
    }
    '/features/clerk/(auth)/sign-up': {
      id: '/features/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/features/clerk/sign-up'
      preLoaderRoute: typeof FeaturesClerkauthSignUpRouteImport
      parentRoute: typeof FeaturesClerkauthRouteRoute
    }
    '/features/clerk/(auth)/sign-in': {
      id: '/features/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/features/clerk/sign-in'
      preLoaderRoute: typeof FeaturesClerkauthSignInRouteImport
      parentRoute: typeof FeaturesClerkauthRouteRoute
    }
    '/features/_authenticated/settings/notifications': {
      id: '/features/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/features/settings/notifications'
      preLoaderRoute: typeof FeaturesAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof FeaturesAuthenticatedSettingsRouteRoute
    }
    '/features/_authenticated/settings/display': {
      id: '/features/_authenticated/settings/display'
      path: '/display'
      fullPath: '/features/settings/display'
      preLoaderRoute: typeof FeaturesAuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof FeaturesAuthenticatedSettingsRouteRoute
    }
    '/features/_authenticated/settings/appearance': {
      id: '/features/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/features/settings/appearance'
      preLoaderRoute: typeof FeaturesAuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof FeaturesAuthenticatedSettingsRouteRoute
    }
    '/features/_authenticated/settings/account': {
      id: '/features/_authenticated/settings/account'
      path: '/account'
      fullPath: '/features/settings/account'
      preLoaderRoute: typeof FeaturesAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof FeaturesAuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

interface FeaturesAuthenticatedSettingsRouteRouteChildren {
  FeaturesAuthenticatedSettingsAccountRoute: typeof FeaturesAuthenticatedSettingsAccountRoute
  FeaturesAuthenticatedSettingsAppearanceRoute: typeof FeaturesAuthenticatedSettingsAppearanceRoute
  FeaturesAuthenticatedSettingsDisplayRoute: typeof FeaturesAuthenticatedSettingsDisplayRoute
  FeaturesAuthenticatedSettingsNotificationsRoute: typeof FeaturesAuthenticatedSettingsNotificationsRoute
  FeaturesAuthenticatedSettingsIndexRoute: typeof FeaturesAuthenticatedSettingsIndexRoute
}

const FeaturesAuthenticatedSettingsRouteRouteChildren: FeaturesAuthenticatedSettingsRouteRouteChildren =
  {
    FeaturesAuthenticatedSettingsAccountRoute:
      FeaturesAuthenticatedSettingsAccountRoute,
    FeaturesAuthenticatedSettingsAppearanceRoute:
      FeaturesAuthenticatedSettingsAppearanceRoute,
    FeaturesAuthenticatedSettingsDisplayRoute:
      FeaturesAuthenticatedSettingsDisplayRoute,
    FeaturesAuthenticatedSettingsNotificationsRoute:
      FeaturesAuthenticatedSettingsNotificationsRoute,
    FeaturesAuthenticatedSettingsIndexRoute:
      FeaturesAuthenticatedSettingsIndexRoute,
  }

const FeaturesAuthenticatedSettingsRouteRouteWithChildren =
  FeaturesAuthenticatedSettingsRouteRoute._addFileChildren(
    FeaturesAuthenticatedSettingsRouteRouteChildren,
  )

interface FeaturesAuthenticatedRouteRouteChildren {
  FeaturesAuthenticatedSettingsRouteRoute: typeof FeaturesAuthenticatedSettingsRouteRouteWithChildren
  FeaturesAuthenticatedIndexRoute: typeof FeaturesAuthenticatedIndexRoute
  FeaturesAuthenticatedAppsIndexRoute: typeof FeaturesAuthenticatedAppsIndexRoute
  FeaturesAuthenticatedChatsIndexRoute: typeof FeaturesAuthenticatedChatsIndexRoute
  FeaturesAuthenticatedHelpCenterIndexRoute: typeof FeaturesAuthenticatedHelpCenterIndexRoute
  FeaturesAuthenticatedTasksIndexRoute: typeof FeaturesAuthenticatedTasksIndexRoute
  FeaturesAuthenticatedUsersIndexRoute: typeof FeaturesAuthenticatedUsersIndexRoute
}

const FeaturesAuthenticatedRouteRouteChildren: FeaturesAuthenticatedRouteRouteChildren =
  {
    FeaturesAuthenticatedSettingsRouteRoute:
      FeaturesAuthenticatedSettingsRouteRouteWithChildren,
    FeaturesAuthenticatedIndexRoute: FeaturesAuthenticatedIndexRoute,
    FeaturesAuthenticatedAppsIndexRoute: FeaturesAuthenticatedAppsIndexRoute,
    FeaturesAuthenticatedChatsIndexRoute: FeaturesAuthenticatedChatsIndexRoute,
    FeaturesAuthenticatedHelpCenterIndexRoute:
      FeaturesAuthenticatedHelpCenterIndexRoute,
    FeaturesAuthenticatedTasksIndexRoute: FeaturesAuthenticatedTasksIndexRoute,
    FeaturesAuthenticatedUsersIndexRoute: FeaturesAuthenticatedUsersIndexRoute,
  }

const FeaturesAuthenticatedRouteRouteWithChildren =
  FeaturesAuthenticatedRouteRoute._addFileChildren(
    FeaturesAuthenticatedRouteRouteChildren,
  )

interface FeaturesClerkauthRouteRouteChildren {
  FeaturesClerkauthSignInRoute: typeof FeaturesClerkauthSignInRoute
  FeaturesClerkauthSignUpRoute: typeof FeaturesClerkauthSignUpRoute
}

const FeaturesClerkauthRouteRouteChildren: FeaturesClerkauthRouteRouteChildren =
  {
    FeaturesClerkauthSignInRoute: FeaturesClerkauthSignInRoute,
    FeaturesClerkauthSignUpRoute: FeaturesClerkauthSignUpRoute,
  }

const FeaturesClerkauthRouteRouteWithChildren =
  FeaturesClerkauthRouteRoute._addFileChildren(
    FeaturesClerkauthRouteRouteChildren,
  )

interface FeaturesClerkAuthenticatedRouteRouteChildren {
  FeaturesClerkAuthenticatedUserManagementRoute: typeof FeaturesClerkAuthenticatedUserManagementRoute
}

const FeaturesClerkAuthenticatedRouteRouteChildren: FeaturesClerkAuthenticatedRouteRouteChildren =
  {
    FeaturesClerkAuthenticatedUserManagementRoute:
      FeaturesClerkAuthenticatedUserManagementRoute,
  }

const FeaturesClerkAuthenticatedRouteRouteWithChildren =
  FeaturesClerkAuthenticatedRouteRoute._addFileChildren(
    FeaturesClerkAuthenticatedRouteRouteChildren,
  )

interface FeaturesClerkRouteRouteChildren {
  FeaturesClerkauthRouteRoute: typeof FeaturesClerkauthRouteRouteWithChildren
  FeaturesClerkAuthenticatedRouteRoute: typeof FeaturesClerkAuthenticatedRouteRouteWithChildren
}

const FeaturesClerkRouteRouteChildren: FeaturesClerkRouteRouteChildren = {
  FeaturesClerkauthRouteRoute: FeaturesClerkauthRouteRouteWithChildren,
  FeaturesClerkAuthenticatedRouteRoute:
    FeaturesClerkAuthenticatedRouteRouteWithChildren,
}

const FeaturesClerkRouteRouteWithChildren =
  FeaturesClerkRouteRoute._addFileChildren(FeaturesClerkRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  FeaturesAuthenticatedRouteRoute: FeaturesAuthenticatedRouteRouteWithChildren,
  FeaturesClerkRouteRoute: FeaturesClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  FeaturesauthForgotPasswordRoute: FeaturesauthForgotPasswordRoute,
  FeaturesauthOtpRoute: FeaturesauthOtpRoute,
  FeaturesauthSignInRoute: FeaturesauthSignInRoute,
  FeaturesauthSignIn2Route: FeaturesauthSignIn2Route,
  FeaturesauthSignUpRoute: FeaturesauthSignUpRoute,
  Featureserrors401Route: Featureserrors401Route,
  Featureserrors403Route: Featureserrors403Route,
  Featureserrors404Route: Featureserrors404Route,
  Featureserrors500Route: Featureserrors500Route,
  Featureserrors503Route: Featureserrors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
